# Generated by Django 2.2.4 on 2019-12-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_actors', models.CharField(max_length=100)),
                ('movie_imdb', models.FloatField()),
                ('production_house', models.CharField(max_length=50)),
            ],
        ),
    ]
