# Generated by Django 2.2.4 on 2020-01-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_house',
        ),
    ]
