# Generated by Django 2.2.4 on 2020-01-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200101_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_imdb',
            field=models.CharField(max_length=10),
        ),
    ]
